### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by letmutx** [wafflespeanut/paperclip#120]
The links to 'addPet operation' and 'id and name fields' are broken. 

https://paperclip.waffles.space/build-script.html#compile-time-checks

**Comment by wafflespeanut** [comment]
Nice find! A worthy first issue.

The problem is with linking directly to master. Changes are to be made in `book/actix-plugin.md` with new links below:

- `addPet` operation: https://github.com/wafflespeanut/paperclip/blob/98a2c053c283ebbbef9b17f7e0ac6ddb0e64f77f/tests/pet-v2.yaml#L125-L148
- `id` and `name` fields: https://github.com/wafflespeanut/paperclip/blob/98a2c053c283ebbbef9b17f7e0ac6ddb0e64f77f/tests/pet-v2.yaml#L44-L46

**Comment by hindenbug** [comment]
@wafflespeanut I can take this up.

**Comment by wafflespeanut** [comment]
@hindenbug You've worked on a relatively harder issue earlier, so I'm guessing this is gonna be very easy for you. :smile: Let's leave this for someone new and I'll try to find a better issue for you to work on?

**Comment by hindenbug** [comment]
@wafflespeanut Haha. Sure :)
