### ISSUE TITLE
no function or associated item named `update_definitions` found for struct `actix_session::Session` in the current scope

### ISSUE THREAD

**Issue by omid** [wafflespeanut/paperclip#231]
Is there any way of fixing this error?

```
error[E0599]: no function or associated item named `update_definitions` found for struct `actix_session::Session` in the current scope
  --> src/main.rs:57:1
   |
57 | #[api_v2_operation]
   | ^^^^^^^^^^^^^^^^^^^ function or associated item not found in `actix_session::Session`
   |
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by wafflespeanut** [comment]
Types from third party (non- actix-web) crates will require paperclip trait implementation either in their crate or in paperclip. I'm completely open about implementing commonly used types on paperclip side. `actix-multipart` is an example. `actix-session` can follow its footsteps (the only difference is that this has nothing OpenAPI-specific, so it just has the empty trait impl). I'd be happy to help if you want to open a PR, otherwise I'll do it over the weekend. :smile:

**Comment by omid** [comment]
Thanks. I'll try to do it tomorrow.
