### ISSUE TITLE
Use deprecated field in actix-web plugin

### ISSUE THREAD

**Issue by platy** [wafflespeanut/paperclip#247]
Writing `#[deprecated]` has been implemented in codegen (in #131), but it could also be used in the plugin the other way around for operations. It would be nice to have it for cody parameters to but that is not supported in openapi.

https://doc.rust-lang.org/edition-guide/rust-2018/the-compiler/an-attribute-for-deprecation.html
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operation-object

**Comment by wafflespeanut** [comment]
Using `#[deprecated]` in codegen makes sense because it'll throw warnings during compilation if the user makes use of the deprecated operation. For server-side, we probably shouldn't use that because the developer is deprecating it in the first place. We can instead have `#[api_v2_operation(deprecated, ...)]` among other things in the macro.

**Comment by platy** [comment]
That makes sense - I'll close this then in favour of adding it with other fields to the macro.
