### ISSUE TITLE
Actix-web: Support 1-tuple structs

### ISSUE THREAD

**Issue by lloydmeta** [wafflespeanut/paperclip#76]
At the moment, it doesn't seem like "newtypes" are supported, e.g.

```rust
#[api_v2_schema)]
#[derive(Serialize, Deserialize)]
pub struct TodoId(pub u64);
```

It would be neat if we could support this, perhaps by making it show as the underlying type in the Swagger spec.

**Comment by wafflespeanut** [comment]
Yeah, I think we can support 1-tuple structs, but it'd be ambiguous for other tuple structs (which lack property names) and unit structs (which lack properties and types).

**Comment by lloydmeta** [comment]
No, thank *you* for being damn awesome. I love this and am using it in a simple-but-not-entirely-trivial PoC/template for API server Rust projects https://github.com/lloydmeta/todddo-openapi-rs

**Comment by wafflespeanut** [comment]
Thanks! That is amazing! :smile:

**Comment by wafflespeanut** [comment]
@hindenbug Would you like to work on this? This requires some changes to paperclip's actix plugin macro, and it's a great way to get into procedural macros. :)

**Comment by hindenbug** [comment]
@wafflespeanut Sure :) I can attempt this.

**Comment by wafflespeanut** [comment]
Great! We're interested in structs with unnamed fields, which are being skipped [here](https://github.com/wafflespeanut/paperclip/blob/4bb0d4fd7ace9fb0a55a373aa8fadd65159c6135/macros/src/actix/mod.rs#L126-L133).

What we should do instead is that if the struct contains exactly one field, then we should use [this block](https://github.com/wafflespeanut/paperclip/blob/4bb0d4fd7ace9fb0a55a373aa8fadd65159c6135/macros/src/actix/mod.rs#L182-L206) to get the type contained within that field (which means, that block should be isolated into a separate function). Once you get that block, you do something like:

```rust
props_gen.extend(quote!({
    schema = #ty_ref::raw_schema();
}));
```

... which will be inserted [here](https://github.com/wafflespeanut/paperclip/blob/4bb0d4fd7ace9fb0a55a373aa8fadd65159c6135/macros/src/actix/mod.rs#L163). However, in order for this to work, [this line](https://github.com/wafflespeanut/paperclip/blob/4bb0d4fd7ace9fb0a55a373aa8fadd65159c6135/macros/src/actix/mod.rs#L162) must be moved to the next line (so that we set the name *after* modifying the schema).

**Comment by hindenbug** [comment]
Hi @wafflespeanut, I began looking into it and have few questions (pardon my lack of in dept rust knowledge atm :) ) 
- so we extract the logic to get the type in a new function ?  
https://github.com/wafflespeanut/paperclip/blob/4bb0d4fd7ace9fb0a55a373aa8fadd65159c6135/macros/src/actix/mod.rs#L182-L206 
- we also need a function for `FieldsUnnamed`, similar to `fn handle_field_struct(fields: &FieldsNamed, props_gen: &mut proc_macro2::TokenStream)` , correct ? 🤔

**Comment by wafflespeanut** [comment]
> ... pardon my lack of in dept rust knowledge atm

No problem!

> so we extract the logic to get the type in a new function ?

Yes, because both [`FieldsNamed`](https://docs.rs/syn/1.0.5/syn/struct.FieldsNamed.html) and [`FieldsUnnamed`](https://docs.rs/syn/1.0.5/syn/struct.FieldsUnnamed.html) have punctuated fields. And, each [`Field`](https://docs.rs/syn/1.0.5/syn/struct.Field.html) has a mandatory type (`ty` field). This function will take that field field as input and return whatever the block currently returns.

> we also need a function for `FieldsUnnamed`, similar to `fn handle_field_struct(fields: &FieldsNamed, props_gen: &mut proc_macro2::TokenStream)`?

Sure. Makes sense.

> or am looking at this wrong

No, you're on the right track. :smile:

**Comment by hindenbug** [comment]
@wafflespeanut I wonder how can we handle the `continue` in the new function :thinking: https://github.com/wafflespeanut/paperclip/blob/4bb0d4fd7ace9fb0a55a373aa8fadd65159c6135/macros/src/actix/mod.rs#L197-L204

**Comment by wafflespeanut** [comment]
Um... `return` early? :smile:

**Comment by lloydmeta** [comment]
Awesome! Thanks @hindenbug and @wafflespeanut !
